w7d5/TrelloClone/config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    resources :users, except: [:new, :create]
    resources :boards
    resources :lists, only: [:create, :update, :destroy]
    resources :cards, only: [:create, :update, :destroy]
  end

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  root to: "static_pages#index"
end

w7d5/TrelloClone/app/models/board.rb
class Board < ActiveRecord::Base
  validates :title, :user, presence: true
  belongs_to :user
  has_many :lists
end

w7d5/TrelloClone/app/models/card.rb
class Card < ActiveRecord::Base
  validates :list, :title, :ord, presence: true
  belongs_to :list
end

w7d5/TrelloClone/app/models/list.rb
class List < ActiveRecord::Base
  validates :title, :board, :ord, presence: true
  belongs_to :board
  has_many :cards
end

w7d5/TrelloClone/app/models/user.rb
class User < ActiveRecord::Base
  validates(
    :username,
    :password_digest,
    :session_token,
    { presence: true, uniqueness: true }
  )
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token
  has_many :boards
  attr_reader :password

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save!
    self.session_token
  end

  def generate_session_token
    SecureRandom.urlsafe_base64
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
end

w7d5/TrelloClone/app/controllers/api/boards_controller.rb
class Api::BoardsController < ApplicationController
  def index
    @boards = Board.where("user_id = ?", current_user.id)
    render :index
  end

  def new
  end

  def create
    @board = Board.new(board_params)
    @board.user_id = current_user.id
    if @board.save
      render :index
    else
      render json: @board.errors.full_messages, status: :unprocessable_entity
    end
  end

  def show
    @board = Board.find(params[:id])
    render 'show'
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def board_params
    params.require(:board).permit(:title)
  end
end

w7d5/TrelloClone/app/controllers/api/cards_controller.rb
class Api::CardsController < ApplicationController

  def create
    @card = Card.new(card_params)
    if @card.save
      render 'show'
    else
      render json: @card.errors.full_messages
    end
  end

  def update
  end

  def destroy
    @card = Card.find(params[:id])
    @card.destroy
    render json: @card
  end

  private
  def card_params
    params.require(:card).permit(:title, :description, :list_id, :ord)
  end
end

w7d5/TrelloClone/app/controllers/api/lists_controller.rb
class Api::ListsController < ApplicationController
  def create
    @list = List.new(list_params)
    if @list.save
      render json: @list
    else
      render json: @list.errors.full_messages
    end
  end

  def update
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    render json: @list
  end

  private
  def list_params
    params.require(:list).permit(:title, :ord, :board_id)
  end
end

w7d5/TrelloClone/app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  def index
    @users = User.all
    render :json => @users
  end

  def show
    @user = User.find(params[:id])
    render :json => @user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      render :json => @user
    else
      render :json => @user.errors.full_messages, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy!
    render :json => @user
  end
end

w7d5/TrelloClone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :logged_in?
  helper_method :current_user

  def login(user)
    session[:session_token] = user.reset_session_token!
    redirect_to root_url
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

  def redirect_if_not_logged_in
    redirect_to new_session_url unless logged_in?
  end
end

w7d5/TrelloClone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(
              user_params[:username],
              user_params[:password]
            )
    if @user
      login(@user)
    else
      flash.now[:errors] = ["Invalid Login Information"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

w7d5/TrelloClone/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

w7d5/TrelloClone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
end

w7d5/TrelloClone/app/helpers/api/boards_helper.rb
module Api::BoardsHelper
end

w7d5/TrelloClone/app/helpers/api/card_helper.rb
module Api::CardHelper
end

w7d5/TrelloClone/app/helpers/api/lists_helper.rb
module Api::ListsHelper
end

w7d5/TrelloClone/app/helpers/api/users_helper.rb
module Api::UsersHelper
end

w7d5/TrelloClone/app/helpers/application_helper.rb
module ApplicationHelper
  def authenticity_token
    html = <<-HTML
      <input type="hidden"
        name="authenticity_token"
        value="#{form_authenticity_token}">
    HTML

    html.html_safe
  end
end

w7d5/TrelloClone/app/helpers/sessions_helper.rb
module SessionsHelper
end

w7d5/TrelloClone/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

w7d5/TrelloClone/app/helpers/users_helper.rb
module UsersHelper
end

w7d5/TrelloClone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrelloClone</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "shared/header" %>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

w7d5/TrelloClone/app/views/shared/_errors.html.erb
<% if flash.now[:errors] %>
  <% flash.now[:errors].each do |error| %>
    <%= error %>
  <% end %>
<% end %>

w7d5/TrelloClone/app/views/shared/_header.html.erb
<header>
  <% if logged_in? %>
    Welcome <%= current_user.username %>!
    <%= button_to "Log Out", session_url, method: :delete %>
  <% else %>
    <%= link_to "Sign In", new_session_url %>
    <%= link_to "Register", new_user_url %>
  <% end %>
</header>

w7d5/TrelloClone/app/views/shared/_newform.html.erb
<% if form_type == "user" %>
  <% action_url = users_url %>
  <% button_text = "Sign Up" %>
<% elsif form_type == "session" %>
  <% action_url = session_url %>
  <% button_text = "Sign In" %>
<% end %>
<%= render "shared/errors" %>
<br>
<br>
<form action="<%= action_url %>" method="post">
  <%= authenticity_token %>
  <label>Username:
    <br>
    <input type="text" name="user[username]">
  </label>

  <br>
  <br>

  <label>Password:
    <br>
    <input type="password" name="user[password]">
  </label>

  <br>
  <br>

  <button type="submit"><%= button_text %></button>
</form>

w7d5/TrelloClone/app/views/static_pages/index.html.erb
<h1>TrelloClone</h1>

<div id="root">
</div>

w7d5/TrelloClone/app/views/users/new.html.erb
<h3>Sign Up!</h3>
<br>
<%= render partial: "shared/newform", locals: { form_type: "user" } %>